import {waveScale,maximumWaveAmplitude} from '../dist/sea-state.js';
import test from 'node:test';
import assert from 'node:assert/strict';
import {createState,step,setSails,steerTo,fireBroadside,repair,changeShipClass,nearestHarbor,buyCannonRefit,PORT,ISLANDS,CARGO,WORLD_LIMIT,distance,waveHeight,RELOAD_TIME} from '../dist/simulation.js';
import {coastRadius,terrainHeight,harborApproach} from '../dist/geography.js';
import {SHIP_CLASSES} from '../dist/ship-classes.js';
const tick=(s,seconds,input={})=>{for(let i=0;i<seconds*60;i++)step(s,1/60,input);};
const isolated=(id='galleon')=>{const s=createState(id);s.enemies=[];s.forts=[];s.x=0;s.z=10;s.started=true;return s;};

test('the voyage waits for player input before enemy combat starts',()=>{const s=createState();tick(s,90);assert.equal(s.time,0);assert.equal(s.hull,100);setSails(s,1);tick(s,1);assert.ok(s.time>.9);});
test('heavy ships accelerate more slowly and keep momentum when sails are furled',()=>{const heavy=isolated(),light=isolated('sloop');for(const s of [heavy,light]){s.angle=0;setSails(s,3);tick(s,2);}assert.ok(light.speed>heavy.speed*1.5);const speed=heavy.speed;setSails(heavy,0);tick(heavy,.5);assert.ok(heavy.speed>speed*.7);assert.ok(Math.hypot(heavy.vx,heavy.vz)>.1);});
test('the rudder builds turning force gradually rather than snapping heading',()=>{const s=isolated();s.angle=0;setSails(s,3);tick(s,5);const before=s.angle;tick(s,.5,{right:true});assert.ok(s.angle>before);assert.ok(s.angle-before<.1);const turning=s.angularVelocity;tick(s,.1);assert.ok(s.angularVelocity>turning*.5);});
test('autopilot recovers cargo and slows to a stop for every class',()=>{for(const id of Object.keys(SHIP_CLASSES)){const s=isolated(id);s.angle=2.72;steerTo(s,CARGO[0].x,CARGO[0].z);tick(s,40);assert.equal(s.cargo,1,id);assert.equal(s.gold,150,id);assert.equal(s.target,null,id);assert.ok(distance(s,CARGO[0])<4,id);assert.ok(s.speed<.1,id);}});
test('each broadside fires every gun once, in random order within its class firing window',()=>{for(const id of Object.keys(SHIP_CLASSES)){const s=isolated(id);assert.equal(fireBroadside(s,'starboard'),true);assert.equal(s.projectiles.length,0);assert.equal(fireBroadside(s,'starboard'),false);const queue=s.salvos.slice();assert.equal(queue.length,SHIP_CLASSES[id].cannons/2);assert.ok(Math.max(...queue.map(g=>g.fireAt))<=(SHIP_CLASSES[id].broadsideDuration||1));assert.equal(new Set(queue.map(g=>g.gun)).size,queue.length);assert.notDeepEqual(queue.map(g=>g.gun),queue.map(g=>g.gun).sort((a,b)=>a-b));tick(s,(SHIP_CLASSES[id].broadsideDuration||1)+.02);assert.equal(s.salvos.length,0);assert.equal(s.events.filter(e=>e.type==='cannon').length,queue.length);}});
test('cannonballs have different aim and speeds, and expire at shorter range',()=>{const s=isolated();s.x=0;s.z=0;s.angle=0;fireBroadside(s,'starboard');tick(s,1);const angles=s.projectiles.map(b=>Math.atan2(b.vx,-b.vz));const speeds=s.projectiles.map(b=>Math.hypot(b.vx,b.vz));assert.ok(Math.max(...angles)-Math.min(...angles)>.025);assert.ok(Math.max(...speeds)<26);assert.ok(Math.max(...speeds)-Math.min(...speeds)>2);tick(s,3.5);assert.equal(s.projectiles.length,0);assert.equal(s.events.filter(e=>e.type==='splash').length,25);assert.ok(s.events.filter(e=>e.type==='splash').every(e=>Math.hypot(e.x,e.z)<78));});
test('several broadsides sink an enemy and award the bounty only once',()=>{
 const s=isolated();s.x=0;s.z=0;s.angle=0;const enemy={id:0,shipClass:'brig',x:23,z:0,angle:0,hull:100,maxHull:100,cooldown:100,homeX:23,homeZ:0};s.enemies=[enemy];
 fireBroadside(s,'starboard');tick(s,3);assert.equal(s.sunk,0);assert.ok(enemy.hull>0&&enemy.hull<100);
 for(let volley=0;volley<4&&enemy.hull>0;volley++){tick(s,RELOAD_TIME);Object.assign(enemy,{x:23,z:0,angle:0,vx:0,vz:0,speed:0});fireBroadside(s,'starboard');tick(s,3);}
 assert.equal(s.sunk,1);assert.equal(s.gold,300);tick(s,RELOAD_TIME);assert.equal(s.sunk,1);assert.equal(s.gold,300);
});
test('hull strength changes damage and a lethal shot ends the voyage',()=>{const losses=[];for(const id of ['sloop','galleon']){const s=isolated(id);s.projectiles=[{x:s.x-1,z:s.z,y:2,vx:23,vz:0,vy:0,life:1,owner:0,damage:5}];step(s,.05);losses.push(100-s.hull);}assert.ok(losses[0]>losses[1]*2);const s=isolated();s.hull=2;s.projectiles=[{x:s.x-1,z:s.z,y:2,vx:23,vz:0,vy:0,life:1,owner:0,damage:5}];step(s,.05);assert.equal(s.hull,0);assert.equal(s.status,'lost');assert.equal(fireBroadside(s),false);});
test('repairs require damaged hull, Nassau, and 100 doubloons',()=>{const s=isolated();s.gold=100;s.hull=40;assert.equal(repair(s),false);Object.assign(s,harborApproach(PORT));assert.equal(repair(s),true);assert.equal(s.hull,100);assert.equal(s.gold,0);assert.equal(repair(s),false);});
test('ship changes work at sea and preserve voyage progress and hull condition',()=>{
 const s=createState();assert.equal(changeShipClass(s,'sloop'),true);s.gold=300;s.cargo=2;s.sunk=1;s.hull=63;s.cannonRefit=true;s.collected.add(2);setSails(s,3);s.x=0;s.z=10;s.cooldown=4;
 assert.equal(nearestHarbor(s),null);assert.equal(changeShipClass(s,'brig'),true);assert.equal(s.shipClass,'brig');assert.equal(s.x,0);assert.equal(s.z,10);assert.equal(s.gold,300);assert.equal(s.cargo,2);assert.equal(s.sunk,1);assert.equal(s.hull,63);assert.equal(s.cooldown,4);assert.equal(s.cannonRefit,true);assert.ok(s.collected.has(2));assert.equal(s.throttle,0);
 assert.equal(changeShipClass(s,'frigate'),true);assert.equal(changeShipClass(s,'galleon'),true);assert.equal(changeShipClass(s,'not-a-ship'),false);s.status='lost';assert.equal(changeShipClass(s,'sloop'),false);
});
test('reef collisions and world bounds stop the ship',()=>{const s=isolated();s.x=ISLANDS[1].x;s.z=ISLANDS[1].z;s.speed=8;s.throttle=3;step(s,.016);assert.ok(distance(s,ISLANDS[1])>=ISLANDS[1].r+2.99);assert.equal(s.hull,94);assert.equal(s.throttle,0);s.x=WORLD_LIMIT+1;step(s,.016);assert.equal(s.x,WORLD_LIMIT);assert.equal(s.vx,0);});
test('winning requires both objectives and Nassau and pays exactly once',()=>{const s=isolated();s.cargo=5;s.sunk=1;Object.assign(s,harborApproach(PORT));step(s,.016);assert.equal(s.status,'playing');s.sunk=2;step(s,.016);assert.equal(s.status,'won');assert.equal(s.gold,1000);tick(s,10);assert.equal(s.gold,1000);});
test('invalid navigation cannot corrupt state and waves remain bounded',()=>{const s=isolated();assert.equal(steerTo(s,NaN,0),false);assert.equal(s.target,null);steerTo(s,1000,-1000);assert.deepEqual(s.target,{x:WORLD_LIMIT,z:-WORLD_LIMIT});for(let i=0;i<100;i++)assert.ok(Math.abs(waveHeight(i,-i,i*.17))<=maximumWaveAmplitude*waveScale()+1e-6);});

test('black market provides discounted repairs and a single cannon refit',()=>{const port=ISLANDS.find(i=>i.kind==='black-market'),s=isolated();Object.assign(s,harborApproach(port));s.gold=575;s.hull=70;assert.equal(nearestHarbor(s),port);assert.equal(repair(s),true);assert.equal(s.gold,500);assert.equal(buyCannonRefit(s),true);assert.equal(s.gold,100);assert.equal(buyCannonRefit(s),false);fireBroadside(s);assert.ok(s.salvos.every(g=>g.damage>SHIP_CLASSES.galleon.damage));});
test('navy forts fire their batteries and do not count as friendly harbours',()=>{const s=createState(),fort=s.forts[0];s.enemies=[];s.forts=[fort];s.started=true;s.time=13;s.x=fort.x-23;s.z=fort.z+24;fort.cooldown=0;assert.equal(nearestHarbor(s),null);tick(s,2);assert.ok(s.events.some(e=>e.type==='cannon'&&e.owner===fort.id));assert.ok(fort.cooldown>0);});
test('silencing a fort pays a bounty without counting as a sunken ship',()=>{const s=isolated(),fort={id:'fort-test',islandSeed:1,x:48,z:-56,hull:1,cooldown:99,staticFort:true,angle:0};s.forts=[fort];s.projectiles=[{x:fort.x-8,z:fort.z,y:2.5,vy:0,vx:23,vz:0,life:1,owner:'player',damage:24}];step(s,.016);assert.ok(fort.hull<=0);assert.equal(s.gold,400);assert.equal(s.sunk,0);step(s,.016);assert.equal(s.gold,400);});
test('natural coastlines meet sea level continuously and slope into the sea',()=>{for(const island of ISLANDS){for(let i=0;i<24;i++){const a=i/24*Math.PI*2,r=coastRadius(island,a),x=Math.cos(a),z=Math.sin(a);assert.ok(Math.abs(terrainHeight(island,x*r,z*r)+.3)<1e-6);assert.ok(terrainHeight(island,x*(r+3),z*(r+3))<-.9);assert.ok(terrainHeight(island,x*(r-6),z*(r-6))>.2);}}});



test('galleon has twenty-five guns per side, a 1.5 second volley and the original seventy damage',()=>{
 const s=isolated();fireBroadside(s,'port');const shots=s.salvos;assert.equal(shots.length,25);assert.equal(SHIP_CLASSES.galleon.cannons,50);assert.ok(Math.abs(shots.reduce((sum,g)=>sum+g.damage,0)-70)<1e-8);assert.ok(Math.max(...shots.map(g=>g.fireAt))>1.35);assert.ok(Math.max(...shots.map(g=>g.fireAt))<=1.5);assert.equal(new Set(shots.map(g=>`${g.along}:${g.muzzleY}`)).size,25);assert.ok(Math.abs(shots.reduce((sum,g)=>sum+g.recoil,0)-14)<1e-8);
 const navy={...s,id:88,cooldown:0};s.salvos=[];fireBroadside(s,'starboard',navy);assert.ok(Math.abs(s.salvos.reduce((sum,g)=>sum+g.damage,0)-42)<1e-8);
});
